"""Offline analysis helpers for persisted AlphaDiana result artifacts."""

from alphadiana.analysis.result_reader import (
    RunBundle,
    load_jsonl_records,
    load_run_bundle,
    resolve_run_relative_path,
)
from alphadiana.analysis.action_events import (
    ACTION_LABEL_CONFIDENCES,
    ACTION_PRIORITY,
    BACKUP_EXCLUDE_PREFIX,
    CANONICAL_ACTIONS,
    DIRECTLLM_CANDIDATES,
    EVENT_SOURCES,
    OBSERVATION_STATUSES,
    PRIMARY_CORPORA,
    TOOL_SUBTYPES,
    ActionEvent,
    classify_action_intent,
    classify_tool_subtype,
    extract_action_event_rows,
    extract_action_events,
    inventory_corpus,
    normalized_records,
    observation_status_from_text,
    select_directllm_baseline,
)
from alphadiana.analysis.action_features import build_record_feature_rows
from alphadiana.analysis.case_studies import (
    CASE_STUDY_MOTIFS,
    select_case_studies,
    summarize_event_sequence,
)
from alphadiana.analysis.clustering import cluster_analysis_views, cluster_rows
from alphadiana.analysis.reliability import compute_reliability_summary
from alphadiana.analysis.reports import render_markdown_report, write_feature_csv, write_json
from alphadiana.analysis.trajectory_metrics import (
    ERROR_STATUSES,
    MAIN_METRIC_NAMES,
    compute_outcome_conditioned_metrics,
    group_event_sequences,
    has_answer_after_verification,
    has_budget_collapse,
    has_error_recovery,
    has_premature_answer,
    has_tool_grounded_reasoning,
    trajectory_key,
)
from alphadiana.analysis.trajectory_reports import (
    render_chinese_discussion,
    render_latex_appendix,
    write_phase14_outputs,
)
from alphadiana.analysis.insight_corpus import (
    CorpusInventoryRow,
    CorpusSpec,
    build_denominator_ledger,
    inventory_corpus_spec,
    load_phase15_corpus_specs,
    load_selected_task_records,
    sanitize_path_text,
    write_denominator_ledger,
)

__all__ = [
    "ACTION_LABEL_CONFIDENCES",
    "ACTION_PRIORITY",
    "BACKUP_EXCLUDE_PREFIX",
    "CANONICAL_ACTIONS",
    "DIRECTLLM_CANDIDATES",
    "EVENT_SOURCES",
    "OBSERVATION_STATUSES",
    "PRIMARY_CORPORA",
    "RunBundle",
    "TOOL_SUBTYPES",
    "ActionEvent",
    "CASE_STUDY_MOTIFS",
    "CorpusInventoryRow",
    "CorpusSpec",
    "ERROR_STATUSES",
    "MAIN_METRIC_NAMES",
    "build_denominator_ledger",
    "build_record_feature_rows",
    "classify_action_intent",
    "classify_tool_subtype",
    "cluster_analysis_views",
    "cluster_rows",
    "compute_outcome_conditioned_metrics",
    "compute_reliability_summary",
    "extract_action_event_rows",
    "extract_action_events",
    "group_event_sequences",
    "has_answer_after_verification",
    "has_budget_collapse",
    "has_error_recovery",
    "has_premature_answer",
    "has_tool_grounded_reasoning",
    "inventory_corpus",
    "inventory_corpus_spec",
    "load_jsonl_records",
    "load_run_bundle",
    "load_phase15_corpus_specs",
    "load_selected_task_records",
    "normalized_records",
    "observation_status_from_text",
    "render_markdown_report",
    "render_chinese_discussion",
    "render_latex_appendix",
    "resolve_run_relative_path",
    "select_case_studies",
    "select_directllm_baseline",
    "sanitize_path_text",
    "summarize_event_sequence",
    "trajectory_key",
    "write_feature_csv",
    "write_json",
    "write_denominator_ledger",
    "write_phase14_outputs",
]
